name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: lmos-cli on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'mandrel'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Set Secret Key
        id: set_secret
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            echo "SECRET_KEY=${{ secrets.LMOS_CLI_SECRET_KEY_WINDOWS }}" >> $GITHUB_ENV
          else
            echo "SECRET_KEY=${{ secrets.LMOS_CLI_SECRET_KEY_NON_WINDOWS }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build (Linux and macOS)
        if: runner.os != 'Windows'
        run: ./gradlew clean build -Dquarkus.native.enabled=true -DLMOS_CLI_SECRET_KEY=$SECRET_KEY

      - name: Set up MSVC on Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: ./gradlew clean build "-Dquarkus.native.enabled=true" "-DLMOS_CLI_SECRET_KEY=$env:SECRET_KEY"
        shell: pwsh

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: lmos-${{ matrix.os }}
          path: build/lmos-cli-*-runner*
